# docker-compose.yml

services:
  detection:
    build:
      context: ./DetectionService
    container_name: detection-service
    ports:
      - "8000:8000"

  recognition:
    build:
      context: ./RecognitionService
    container_name: recognition-service
    ports:
      - "8001:8001"

  