global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'detection-service'
    static_configs:
      - targets: ['detection:8000']

  - job_name: 'recognition-service'
    static_configs:
      - targets: ['recognition:8001']

  - job_name: 'hardware-metrics'
    static_configs:
      - targets: ['metrics-collector:9100']